// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjzoysezwarkbcuvwfex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indqem95c2V6d2Fya2JjdXZ3ZmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5ODU3ODUsImV4cCI6MjA5MTU2MTc4NX0.HPyTW9FfElU-vcGA7Ufn8zWaaCg-c1rDerXYP57baa4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});